version: '3.8'
services:
  jalasoft:
    container_name: jalasoft
    restart: always
    image: docker.jala.pro/websites/jalasoft:3.0-POC-TEST
    ports:
      - 3000:3000
    networks:
      - websites
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
      - CONTENTFUL_ACCESS_KEY=${CONTENTFUL_ACCESS_KEY}
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_HOST=${CONTENTFUL_HOST}
      - REVALIDATE_TIME=${REVALIDATE_TIME}
    volumes:
      - ./logs_data:/app/packages/jalasoft/logs

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - websites
    environment:
      NGINX_PROXY_PASS: |
        http://localhost -> http://jalasoft:3000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  watchtower:
      image: containrrr/watchtower
      environment:
        - WATCHTOWER_CLEANUP=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $HOME/.docker/config.json:/config.json
      command: --interval 30
networks:
  websites:
    driver: bridge
volumes:
  logs_data:
