version: "3.9"

services: 
 nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./dhparam.pem:/etc/nginx/dhparam.pem
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
networks:
  default:
    name: kit_directus
    external: true
