name: Build Containers for test & Push to Dockerhub
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-back:
    name: Build and Deploy Jalasoft site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.jala.pro
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}"
            "CONTENTFUL_ACCESS_KEY=${{ secrets.CONTENTFUL_ACCESS_KEY }}"
            "NEXT_PUBLIC_APP_ENV=${{NEXT_PUBLIC_APP_ENV}}"
            "CONTENTFUL_HOST=${{CONTENTFUL_HOST}}"
          push: true
          tags: docker.jala.pro/websites/jalasoft:2.0-POC
